fit_brms_for_sampling_rate_rstan <- function(data, 
                                             priors = set_prior("normal(0,1000)", class = "b"),
                                             formula,
                                             warmup = 2000,
                                             iter = 10000,
                                             chains = 4,
                                             cores = 4,
                                             threads = threading(2),
                                             seed = NA,
                                             control = NULL
){
  brm(data = data,
      formula = formula,
      warmup = warmup,
      iter = iter,
      chains = chains,
      prior = priors,
      sample_prior = "yes",
      family = exgaussian(),
      #init = "0",
      #control = list(adapt_delta =  0.8),
      #      control = list(refresh = 100),
      cores = cores,
      #      backend = "cmdstanr",
      #      threads = threads,
      seed = seed,
      silent = 0)
}
